### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by A** [davidosomething/enhanced-resolve-cli#7]
Seems like it should work, but it doesn't. Don't hesitate to ask any details :)

```js
$ enhancedresolve -w ./_scripts/react-scripts/config/webpack.config.dev.js -d core/components/Panel
[DEBUG] Basepath:  /Users/anton.shuvalov/Projects/web-apps
[DEBUG] Webpack config file:  ./_scripts/react-scripts/config/webpack.config.dev.js
[DEBUG] Webpack module:  /Users/anton.shuvalov/Projects/web-apps/node_modules/webpack/lib/webpack.js
[ERROR] Could not resolve core/components/Panel from /Users/anton.shuvalov/Projects/web-apps
$ cat ./_scripts/react-scripts/config/webpack.config.dev.js | grep -B10 core | grep -v "//"
    alias: {
      'babel-runtime': path.dirname(
        require.resolve('babel-runtime/package.json')
      ),
      'accounts': 'accounts/src',
      'core': 'core/src',
$
```

**Comment by davidosomething** [comment]
yea i stopped using this actually, was easier to just configure language server to resolve things for me
want to take over it?

**Comment by A** [comment]
> configure language server

@davidosomething thx for answer. what do you mean? Could you drop a link or something?

**Comment by davidosomething** [comment]
the point of this module was to use as a filepath resolver in vim
but vim can just use language server instead (https://langserver.org/) through various plugins, and that can be configured to properly resolve file paths.

the module itself can still be useful outside of that intended use, but i have no reason to do it any more
